# Generated by Django 4.2 on 2023-12-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_alter_prime_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('duree', models.IntegerField(verbose_name='Duree')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('date_achat', models.DateField(verbose_name='Date Achat ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilites', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('mois', models.DateField(verbose_name='Mois')),
                ('somme', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Somme')),
                ('facilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='facilities.facilite', verbose_name='Facitite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
