# Generated by Django 4.2 on 2023-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_prime_employee'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='is_commited',
            field=models.BooleanField(default=False, verbose_name='is ommit'),
        ),
        migrations.AlterUniqueTogether(
            name='facilite',
            unique_together={('employee', 'date_achat')},
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('facilite', 'mois')},
        ),
    ]
