# Generated by Django 4.2 on 2023-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_timeline_is_commited_alter_facilite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilite',
            name='is_completed',
            field=models.BooleanField(default=1, verbose_name='Is Completed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeline',
            name='is_commited',
            field=models.BooleanField(default=False, verbose_name='is commit'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='mois',
            field=models.DateField(unique_for_month=True, verbose_name='Mois'),
        ),
    ]
