# Generated by Django 4.2 on 2023-12-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_prime_employee'),
        ('facilities', '0003_facilite_is_completed_alter_timeline_is_commited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='mois',
            field=models.DateField(verbose_name='Mois'),
        ),
        migrations.AlterUniqueTogether(
            name='facilite',
            unique_together={('employee', 'date_achat', 'is_completed')},
        ),
    ]
