# Generated by Django 4.2 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_timeline_mois_alter_facilite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='month',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, max_length=50, verbose_name='month'),
            preserve_default=False,
        ),
    ]
