# Generated by Django 4.2 on 2023-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_timeline_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilite',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='facilite',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='month',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50, verbose_name='month'),
        ),
    ]
