# Generated by Django 4.2 on 2023-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facilite_observation_alter_facilite_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Color'),
        ),
    ]
