# Generated by Django 4.2 on 2023-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_timeline_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timeline',
            constraint=models.UniqueConstraint(fields=('facilite', 'mois'), name='name of constraint'),
        ),
    ]
