# Generated by Django 4.2 on 2024-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_alter_timeline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
