# Generated by Django 4.2 on 2024-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_timeline_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='background',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Background'),
        ),
    ]
