# Generated by Django 4.2 on 2024-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_timeline_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Color')),
                ('background', models.CharField(blank=True, max_length=10, null=True, verbose_name='background')),
            ],
        ),
    ]
