# Generated by Django 4.2 on 2024-07-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_cellstyle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilite',
            unique_together=set(),
        ),
    ]
