# Generated by Django 4.2 on 2024-01-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_delete_prime_delete_primetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_open', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_f', models.DateField(blank=True, null=True, verbose_name='date de fete')),
                ('date_r', models.DateField(blank=True, null=True, verbose_name='date de reception')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primes', to='employees.employee', verbose_name='Employee')),
                ('prime_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='primes.primetype', verbose_name='Prime Type')),
                ('proces_v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='primes.procesverbal', verbose_name='Proces Verbal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
