# Generated by Django 4.2 on 2024-01-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='proces_v',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primes.procesverbal', verbose_name='Proces Verbal'),
        ),
    ]
