# Generated by Django 4.2 on 2024-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primes', '0002_alter_prime_proces_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesverbal',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='procesverbal',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Is Open'),
        ),
    ]
