# Generated by Django 4.2 on 2023-12-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Direction Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('matricule', models.IntegerField(verbose_name='Matricule')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom')),
                ('date_n', models.DateField(verbose_name='Date de Naissance')),
                ('date_e', models.DateField(verbose_name="Date d'entrée")),
                ('poste', models.CharField(max_length=255, verbose_name='Poste')),
                ('fin_contrat', models.DateField(verbose_name="Date d'entrée")),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], max_length=50, verbose_name='Type Contrat')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
