# Generated by Django 4.2 on 2023-12-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_n',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.direction', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fin_contrat',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste'),
        ),
    ]
