# Generated by Django 4.2 on 2023-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_primetype_alter_employee_fin_contrat_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.IntegerField(unique=True, verbose_name='Matricule'),
        ),
    ]
