# Generated by Django 4.2 on 2023-12-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primes', to='employees.employee', verbose_name='Employee'),
        ),
    ]
