# Generated by Django 4.2 on 2024-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_prime_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prime',
        ),
        migrations.DeleteModel(
            name='Primetype',
        ),
    ]
