# Generated by Django 4.2 on 2024-06-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_delete_prime_delete_primetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.direction', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type_contrat',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Stage', 'Stage')], max_length=50, verbose_name='Type Contrat'),
        ),
    ]
