# Generated by Django 4.2 on 2024-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_direction_alter_employee_type_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_e',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
    ]
