# Generated by Django 4.2 on 2023-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VENDOR', 'VENDOR'), ('CUSTOMER', 'CUSTOMER'), ('SUB_ADMIN', 'SUB_ADMIN'), ('SUPER_ADMIN', 'SUPER_ADMIN')], default='CUSTOMER', max_length=50),
        ),
    ]
